import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import Countdown from "../countdown/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <Image
                        src={"/ntf-page-image.png"}
                        width={1280}
                        height={560}
                        alt="NTF"
                    />
                <div className="flex justify-between items-center">
                    {children}
                    <div className="relative flex">
                        <Countdown />
                    </div>
                </div>
            </body>
        </html>
    );
}
