import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import Countdown from "../countdown/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="relative flex-col justify-center items-center">
                    {children}
                    <div className="absolute top-0 right-0">
                        <Countdown />
                    </div>
                </div>
            </body>
        </html>
    );
}
